# Generated by Django 2.2.2 on 2020-08-25 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
