# Generated by Django 2.2.2 on 2020-08-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0003_auto_20200825_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cart_id',
            field=models.IntegerField(default=0),
        ),
    ]
