# Generated by Django 2.2.2 on 2020-08-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0004_cart_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='prodid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
