# Generated by Django 2.2.2 on 2020-08-25 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0005_auto_20200825_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='prodid',
            field=models.CharField(max_length=10),
        ),
    ]
