# Generated by Django 2.2.2 on 2020-08-25 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0006_auto_20200825_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(default='', max_length=255),
        ),
    ]
