# Generated by Django 2.2.2 on 2020-09-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0007_auto_20200825_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Order Date')),
                ('order', models.CharField(max_length=20, verbose_name='Order id')),
                ('address', models.TextField(verbose_name='Delivery Address')),
                ('items', models.TextField(verbose_name='Items Ordered')),
                ('status', models.CharField(max_length=20, verbose_name='Status')),
            ],
        ),
    ]
