# Generated by Django 2.2.2 on 2020-09-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0010_auto_20200917_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Order Date'),
        ),
    ]
