# Generated by Django 2.2.2 on 2020-09-19 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irish', '0012_auto_20200919_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='prodid',
            field=models.CharField(default='prod0', max_length=10),
        ),
    ]
