# Generated by Django 2.2.2 on 2020-09-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('irish', '0008_shipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_created=True, verbose_name='Refill Date')),
                ('quantity', models.IntegerField(verbose_name='Refill Quantity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irish.Product')),
            ],
        ),
    ]
