# Generated by Django 2.2.2 on 2020-09-16 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('username', models.CharField(max_length=20, verbose_name='Username')),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
                ('image', models.FileField(upload_to='', verbose_name='Image')),
            ],
        ),
    ]
