# Generated by Django 2.2.2 on 2020-09-16 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adumin', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
