# Generated by Django 2.2.2 on 2020-09-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adumin', '0003_delete_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refill',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Refill Date'),
        ),
    ]
